  version: '3.1'

  networks:
    kafka_network:
      external: true

  services:
    zookeeper:
      image: 'bitnami/zookeeper:latest'
      ports:
        - '2181:2181'
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
      healthcheck:
        test: [ "CMD", "nc", "-vz", "localhost", "2181" ]
        interval: 10s
        timeout: 3s
        retries: 3
      networks:
        - kafka_network

    kafka:
      image: 'bitnami/kafka:latest'
      ports:
        - '9092:9092'
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_LISTENERS=PLAINTEXT://:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper
      healthcheck:
        test: [ "CMD", "nc", "-vz", "localhost", "9092" ]
        interval: 10s
        timeout: 3s
        retries: 3
      networks:
        - kafka_network

    postgresqldb:
      image: postgres
      restart: unless-stopped
      env_file: ./.env
      ports:
        - ${POSTGRESQL_LOCAL_PORT}:${POSTGRESQL_DOCKER_PORT}
      environment:
        POSTGRES_PASSWORD: ${POSTGRESQL_ROOT_PASSWORD}
        POSTGRES_DB: ${POSTGRESQL_DATABASE}
        POSTGRES_USER: ${POSTGRESQL_USER}
      networks:
        - kafka_network

    kafka-order:
      build: .
      ports:
        - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
        - ${DEBUG_PORT}:${DEBUG_PORT}
      depends_on:
        - kafka
        - postgresqldb
      env_file: ./.env
      restart: on-failure
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:postgresql://postgresqldb:${POSTGRESQL_DOCKER_PORT}/${POSTGRESQL_DATABASE}",
          "spring.datasource.username": "${POSTGRESQL_USER}",
          "spring.datasource.password": "${POSTGRESQL_PASSWORD}",
          "spring.datasource.driver-class-name": "org.postgresql.Driver",
          "spring.jpa.hibernate.ddl-auto": "validate",
          "spring.jpa.show-sql": "true",
          "server.servlet.context-path": "/api",
          "spring.main.allow-bean-definition-overriding":"true"
          }'
        JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      networks:
        - kafka_network
